# Generated by Django 3.1 on 2020-08-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Branch', models.CharField(max_length=10)),
                ('Mobile', models.CharField(max_length=10)),
                ('Email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
