# Generated by Django 3.1 on 2020-08-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Faculty',
        ),
    ]
