# Generated by Django 3.1 on 2020-08-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0002_auto_20200812_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='Branch',
            field=models.CharField(choices=[('ECE', 'ece'), ('CSE', 'cse'), ('IT', 'it'), ('EEE', 'eee')], max_length=10),
        ),
    ]
